name: Build

on:
  workflow_dispatch:
    inputs:
      update_deps:
        description: 'Update deps?'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
      
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Update Dependencies
        run: npm update --legacy-peer-deps
        if: ${{ inputs.update_deps }}

      - name: Build Scratch
        run: npm run build
      
      - name: Upload the pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Publish Pages
        id: deployment
        uses: actions/deploy-pages@v4
